name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: $${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: /public_html/
        excluse: |
          **/.git*
          **/.git*/**
          **/.github*/**
          .editconfig
          site/cache/**
          site/sessions/**
    
    - name: Clear Kirby Cache
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        remoteFiles: /public_html/site/cache/reacien.dev/
        ignoreDirectoryPath: true